// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=./mocks/mocks.go -package=repomocks
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ryl1k/INT20H-test-task-server/internal/entity"
	dto "github.com/ryl1k/INT20H-test-task-server/internal/repo/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
	isgomock struct{}
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockOrderRepo) BatchCreate(ctx context.Context, orders []entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, orders)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockOrderRepoMockRecorder) BatchCreate(ctx, orders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockOrderRepo)(nil).BatchCreate), ctx, orders)
}

// Create mocks base method.
func (m *MockOrderRepo) Create(ctx context.Context, order entity.Order) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepoMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepo)(nil).Create), ctx, order)
}

// DeleteAll mocks base method.
func (m *MockOrderRepo) DeleteAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockOrderRepoMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockOrderRepo)(nil).DeleteAll), ctx)
}

// GetAll mocks base method.
func (m *MockOrderRepo) GetAll(ctx context.Context, filter dto.OrderFilters) (entity.OrderList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, filter)
	ret0, _ := ret[0].(entity.OrderList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderRepoMockRecorder) GetAll(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderRepo)(nil).GetAll), ctx, filter)
}

// GetById mocks base method.
func (m *MockOrderRepo) GetById(ctx context.Context, id int) (entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockOrderRepoMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockOrderRepo)(nil).GetById), ctx, id)
}

// MockTaxRepo is a mock of TaxRepo interface.
type MockTaxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaxRepoMockRecorder
	isgomock struct{}
}

// MockTaxRepoMockRecorder is the mock recorder for MockTaxRepo.
type MockTaxRepoMockRecorder struct {
	mock *MockTaxRepo
}

// NewMockTaxRepo creates a new mock instance.
func NewMockTaxRepo(ctrl *gomock.Controller) *MockTaxRepo {
	mock := &MockTaxRepo{ctrl: ctrl}
	mock.recorder = &MockTaxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxRepo) EXPECT() *MockTaxRepoMockRecorder {
	return m.recorder
}

// GetTaxByLocation mocks base method.
func (m *MockTaxRepo) GetTaxByLocation(ctx context.Context, lat, lon float64) (*entity.JurisdictionTax, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxByLocation", ctx, lat, lon)
	ret0, _ := ret[0].(*entity.JurisdictionTax)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTaxByLocation indicates an expected call of GetTaxByLocation.
func (mr *MockTaxRepoMockRecorder) GetTaxByLocation(ctx, lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxByLocation", reflect.TypeOf((*MockTaxRepo)(nil).GetTaxByLocation), ctx, lat, lon)
}
